# Generated by Django 5.2.16 on 2026-07-12 17:53

import django.db.models.deletion
import django_telegram_q2.common.fields
import django_telegram_q2.telegram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "telegram_api_token",
                    django_telegram_q2.common.fields.EncryptedCharField(max_length=512),
                ),
                (
                    "webhook_secret",
                    django_telegram_q2.common.fields.EncryptedCharField(
                        default=django_telegram_q2.telegram.models.generate_webhook_secret,
                        max_length=64,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("telegram_update_offset", models.IntegerField(default=0)),
                ("webhook_enabled_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_disabled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bot",
                "verbose_name_plural": "Bots",
                "db_table": "telegram_bot",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IntakeBuffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(max_length=255)),
                (
                    "reply_to_message_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("text", models.TextField()),
                ("message_count", models.PositiveIntegerField(default=1)),
                ("last_message_ts", models.PositiveBigIntegerField()),
                ("last_received_at", models.DateTimeField()),
                ("flushed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="telegram.bot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Intake Buffer",
                "verbose_name_plural": "Intake Buffers",
                "db_table": "telegram_intakebuffer",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("flushed_at__isnull", True)),
                        fields=("bot", "chat_id"),
                        name="tg_uniq_open_intake_buffer_per_bot_chat",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply_target", models.TextField()),
                (
                    "reply_to_message_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("raw_input", models.TextField()),
                ("raw_output", models.TextField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("delivery_error", models.TextField(blank=True, null=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("processing_finished_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_started_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="telegram.bot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "db_table": "telegram_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            ("processing_error__isnull", True),
                            ("processing_finished_at__isnull", True),
                            ("processing_started_at__isnull", True),
                        ),
                        fields=["created_at", "id"],
                        name="tg_job_ready_processing_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("processing_error__isnull", True),
                            ("processing_finished_at__isnull", True),
                            ("processing_started_at__isnull", False),
                        ),
                        fields=["processing_started_at"],
                        name="tg_job_stale_processing_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("delivery_finished_at__isnull", True),
                            ("delivery_started_at__isnull", True),
                            ("processing_finished_at__isnull", False),
                            models.Q(
                                ("raw_output__isnull", False),
                                ("processing_error__isnull", False),
                                _connector="OR",
                            ),
                        ),
                        fields=["processing_finished_at", "id"],
                        name="tg_job_ready_delivery_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("raw_output__isnull", True),
                            ("processing_finished_at__isnull", False),
                            _connector="OR",
                        ),
                        name="tg_job_raw_output_requires_processing_finished",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("processing_finished_at__isnull", True),
                            ("raw_output__isnull", False),
                            ("processing_error__isnull", False),
                            _connector="OR",
                        ),
                        name="tg_job_processing_finished_requires_result_or_error",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("processing_finished_at__isnull", True),
                            ("processing_started_at__isnull", False),
                            _connector="OR",
                        ),
                        name="tg_job_processing_finished_requires_started",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("delivery_started_at__isnull", True),
                            models.Q(
                                ("processing_finished_at__isnull", False),
                                models.Q(
                                    ("raw_output__isnull", False),
                                    ("processing_error__isnull", False),
                                    _connector="OR",
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="tg_job_delivery_started_requires_output",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("delivery_finished_at__isnull", True),
                            ("delivery_started_at__isnull", False),
                            _connector="OR",
                        ),
                        name="tg_job_delivery_finished_requires_started",
                    ),
                ],
            },
        ),
    ]
